### PR TITLE
Tidied up the style for the login page

### PR DESCRIPTION
**Pull request by matthewgrossman**
## What

Fixed up the look for the login page. I do think it could still use some refinement, but now we have the logo, company name, pretty buttons, and pretty edittexts. Also, the colors were changed globally to use parq-purple (which is now what we will call it)

### CODE REVIEW

**Comment by nickcharles** [comment]
Doesn't look like this includes the resources for the logo or the company icon.

**Comment by matthewgrossman** [comment]
Just added the resources, sorry bout that

**Comment by matthewgrossman** [comment]
just rebased

**Comment by nickcharles** [comment]
Merge it :fire:

**Pull request merged**
