### PR TITLE
Implements navigation in gmaps & displays occupied card after returning

### PR DESCRIPTION
**Pull request by kenzshelley**
<h1> What? </h1>
- Clicking on 'Navigate to spot' in the driver home fragment opens navigation to the spot in google maps
- After returning from navigation, the home fragment displays a card including info about the spot, the amount of time the spot has been occupied, and the net cost

image

<h1> Related pending issues: </h1> 
#6 #7

@matthewgrossman @nickcharles

### CODE REVIEW

**Comment by nickcharles** [comment]
Maybe I'm crazy, but as I'm playing with it, when I click leave spot this takes me into Google Maps again.

**Comment by kenzshelley** [comment]
So I was thinking about not merging this because my next PR obsoletes a lot of it.....but I think I'm going to go ahead and do it anyways so that my next one isn't enormous.

**Comment by kenzshelley** [comment]
Oh and yes @nickcharles is right --- there's a bug w/ the button that makes it continuously enter navigation, next PR will fix that though!

**Comment by kenzshelley** [comment]
:ship:

**Pull request merged**
