### PR TITLE
Nick/host ui improvements

### PR DESCRIPTION
**Pull request by nickcharles**
The host side of things is now beautiful.

@kenzshelley @matthewgrossman

### CODE REVIEW

**Comment by kenzshelley** [comment]
Looks good! Only suggestion is maybe make the 'Create spot' button on the new spot page a bit bigger, and make sure the text is centered vertically inside it

**Comment by nickcharles** [comment]
Didn't even notice that, I'll make the fix. Honestly I don't really like that page anyway, I figure Max might be able to spruce it up a bit.

**Comment by matthewgrossman** [comment]
Do we need to make an appointment with max? or do we just show up?

**Comment by nickcharles** [comment]
Wouldn't hurt to make an appointment.

**Pull request merged**
